name: Custom github action test

on:
  push:
    branches: .*

jobs:
  test-custom-action:
    name: Test custom action
    runs-on: macos-15

    steps:
      - name: Test custom action
        uses: Filozoff/action-swift-propose-next-version@master
