name: Custom github action test

on:
  push:
    branches: .*

env:
  DEVELOPER_DIR: "/Applications/Xcode_16.2.app/Contents/Developer"

jobs:
  test:
    name: Test custom action
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Propose next version
        run: sh ./Scripts/run_tests.sh
