name: Custom github action test

on:
  push:
    branches: []

env:
  DEVELOPER_DIR: "/Applications/Xcode_16.0.app/Contents/Developer"
  TARGET_DEVICE: "platform=iOS Simulator,name=iPhone 16,OS=18.0"
  TARGET_SCHEME: "XCTestExtension"

jobs:
  test-custom-action:
    name: Test custom action
    runs-on: macos-15
    outputs:
      next-version: ${{ steps.test-action.outputs.proposed-next-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Test custom action
        id: test-action
        uses: Filozoff/action-swift-propose-next-version@v1
        with:
          device: "${{ env.TARGET_DEVICE }}"
          scheme: "${{ env.TARGET_SCHEME }}"

  push-tag:
    name: Create and push tag
    needs: test-custom-action
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Push tag
        uses: Filozoff/action-make-tag@v1
        with:
          commit-sha: "${{ github.sha }}"
          tag: ${{ needs.test-custom-action.outputs.next-version }}
          token: ${{ secrets.TAG_TOKEN }}

