name: CI

on:
  push:
    branches: [ "master" ]
    paths: ['.github/workflows/**', 'Package.swift', 'Scripts/**', 'Sources/**', 'Tests/**']

jobs:
  test:
    name: CI test
    runs-on: macos-12
    env:
      DEVELOPER_DIR: "/Applications/Xcode_14.0.app/Contents/Developer"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        run: sh ./Scripts/run_tests.sh

      - name: Code coverage
        run: sh ./Scripts/code_coverage.sh

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./.coverage/
          fail_ci_if_error: true
          verbose: true
