name: CI

on:
  push:
    branches: [ "master" ]
    paths: ['.github/workflows/**', 'Package.swift', 'Scripts/**', 'Sources/**', 'Tests/**']

jobs:
  test:
    name: CI test
    uses: ./.github/workflows/pr-check.yml

  code-coverage:
    name: "Code coverage"
    runs-on: macos-12
    steps:
      - name: Code coverage
        run: sh ./Scripts/code_coverage.sh

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./.coverage/
          fail_ci_if_error: true
          verbose: true
