name: CI

on:
  push:
    branches: [ "master" ]

env:
  DEVELOPER_DIR: "/Applications/Xcode_16.0.app/Contents/Developer"

jobs:
  test:
    name: CI test
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: make test -s

      - name: Get coverage
        run: make code-coverage -s

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./.coverage/
          fail_ci_if_error: true
          verbose: true

  documentation:
    name: Deploy documentation
    needs: test
    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: true

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build DocC
        run: make documentation -s

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'

      - name: Deploy on GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
