name: CI

on:
  push:
    branches: [ "master" ]

env:
  DEVELOPER_DIR: "/Applications/Xcode_16.0.app/Contents/Developer"
  TARGET_DEVICE: "platform=iOS Simulator,name=iPhone 16,OS=18.0"
  TARGET_SCHEME: "XCTestExtension"

jobs:
  test:
    name: CI test
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: make test -s

      - name: Get coverage
        run: make code-coverage -s

      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./.coverage/
          fail_ci_if_error: true
          verbose: true

  propose-next-version:
    name: Propose next version
    needs: test
    runs-on: macos-15
    outputs:
      next-version: ${{ steps.next-version.outputs.proposed-next-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Get next version
        id: next-version
        uses: Filozoff/action-swift-propose-next-version@v1
        with:
          device: "${{ env.TARGET_DEVICE }}"
          scheme: "${{ env.TARGET_SCHEME }}"

  push-tag:
    name: Create and push tag
    needs: propose-next-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Push tag
        uses: Filozoff/action-make-tag@v1
        with:
          commit-sha: "${{ github.sha }}"
          tag: ${{ needs.propose-next-version.outputs.next-version }}
          token: ${{ secrets.TAG_TOKEN }}

  documentation:
    name: Deploy documentation
    needs: push-tag
    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: true

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build DocC
        run: make documentation -s

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'

      - name: Deploy on GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
