name: PR Check

on:
  pull_request:
    branches: [ "master" ]
  workflow_call:

env:
  DEVELOPER_DIR: "/Applications/Xcode_16.0.app/Contents/Developer"

jobs:
  test:
    name: Test
    runs-on: macos-15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run tests
      run: make test -s
